/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.cadastroExEpiController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Fabinhu
 */
public class cadastroExcecaoEPI extends javax.swing.JFrame {

    /**
     * Creates new form cadastroExcecaoEPI
     */
    
     private final cadastroExEpiController controller;
    
    public cadastroExcecaoEPI() {
        initComponents();
        controller = new cadastroExEpiController(this);
        controller.ocultarCamposEx();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        consultaFuncionarioEx = new javax.swing.JTextField();
        paneTabelaConsultaEx = new javax.swing.JScrollPane();
        tabelaConsultaEx = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        codFuncionarioEx = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        chapaFuncionarioEx = new javax.swing.JTextField();
        nomeFuncionarioEx = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cpfFuncionarioEx = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rgFuncionarioEx = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dataAdmissaoEx = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        empresaFuncionarioEx = new javax.swing.JTextField();
        ocultoIdEmpresaFuncionario = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        nomeSetorFuncEx = new javax.swing.JTextField();
        ocultoSetorIdEx = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        paneTabelaEpiSetorEx = new javax.swing.JScrollPane();
        TabelaEpiSetorEx = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        observacaoFuncionarioEx = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        riscosetorEx = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ConsultaEpiEx = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        qtdEpiEx = new javax.swing.JTextField();
        botaoAdicionarEx = new javax.swing.JButton();
        ocultoIdEpi = new javax.swing.JTextField();
        paneEpíEx = new javax.swing.JScrollPane();
        tabelaEpiEx = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        paneTabelaEpiEx = new javax.swing.JScrollPane();
        tabelaEpiSetorFuncionarioEx = new javax.swing.JTable();
        botaoRemoverTabelaEx = new javax.swing.JButton();
        botaoAtualizarTabelaEx = new javax.swing.JButton();
        botaoSalvarEx = new javax.swing.JButton();
        botaoCancelarEx = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Exceção de Uso de EPI");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Funcionario");

        consultaFuncionarioEx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                consultaFuncionarioExKeyReleased(evt);
            }
        });

        tabelaConsultaEx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaConsultaEx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaConsultaExMouseClicked(evt);
            }
        });
        paneTabelaConsultaEx.setViewportView(tabelaConsultaEx);

        jLabel3.setText("Codigo");

        jLabel4.setText("Chapa");

        jLabel5.setText("Nome");

        jLabel6.setText("CPF");

        jLabel7.setText("RG");

        jLabel8.setText("Data Adm.");

        jLabel10.setText("Empesa");

        jLabel16.setText("Setor");

        jLabel19.setText("Cód. Setor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(ocultoIdEmpresaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paneTabelaConsultaEx, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consultaFuncionarioEx, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(empresaFuncionarioEx, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(11, 11, 11)
                                            .addComponent(jLabel3))
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(codFuncionarioEx, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(chapaFuncionarioEx, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(dataAdmissaoEx, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(nomeFuncionarioEx)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(cpfFuncionarioEx, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rgFuncionarioEx))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addComponent(jLabel6)))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel19)
                            .addGap(18, 18, 18)
                            .addComponent(ocultoSetorIdEx, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nomeSetorFuncEx))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(consultaFuncionarioEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(ocultoIdEmpresaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneTabelaConsultaEx, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(codFuncionarioEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(chapaFuncionarioEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(dataAdmissaoEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nomeFuncionarioEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cpfFuncionarioEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(rgFuncionarioEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeSetorFuncEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(ocultoSetorIdEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empresaFuncionarioEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EPI Utilizados");

        TabelaEpiSetorEx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EPI", "Qtd."
            }
        ));
        paneTabelaEpiSetorEx.setViewportView(TabelaEpiSetorEx);

        observacaoFuncionarioEx.setColumns(20);
        observacaoFuncionarioEx.setLineWrap(true);
        observacaoFuncionarioEx.setRows(5);
        jScrollPane4.setViewportView(observacaoFuncionarioEx);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Observações Funcionario");

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("RISCO SETOR");

        riscosetorEx.setColumns(20);
        riscosetorEx.setLineWrap(true);
        riscosetorEx.setRows(5);
        jScrollPane5.setViewportView(riscosetorEx);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeAtencao24px.png"))); // NOI18N
        jLabel9.setText("   ATENÇÃO");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeAtencao24px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(paneTabelaEpiSetorEx, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneTabelaEpiSetorEx, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setText("Consulta");

        jLabel12.setText("EPI");

        ConsultaEpiEx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ConsultaEpiExKeyReleased(evt);
            }
        });

        jLabel13.setText("Quantidade");

        botaoAdicionarEx.setText("Adicionar");
        botaoAdicionarEx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoAdicionarExMouseClicked(evt);
            }
        });

        tabelaEpiEx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaEpiEx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaEpiExMouseClicked(evt);
            }
        });
        paneEpíEx.setViewportView(tabelaEpiEx);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(15, 15, 15)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ConsultaEpiEx)
                            .addComponent(paneEpíEx, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ocultoIdEpi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(qtdEpiEx, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(botaoAdicionarEx, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ConsultaEpiEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneEpíEx, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(ocultoIdEpi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(qtdEpiEx, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaoAdicionarEx, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tabelaEpiSetorFuncionarioEx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EPI", "Qtd.", "Autorizado"
            }
        ));
        paneTabelaEpiEx.setViewportView(tabelaEpiSetorFuncionarioEx);

        botaoRemoverTabelaEx.setText("Remover");
        botaoRemoverTabelaEx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoRemoverTabelaExMouseClicked(evt);
            }
        });

        botaoAtualizarTabelaEx.setText("Atualizar");
        botaoAtualizarTabelaEx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoAtualizarTabelaExMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneTabelaEpiEx)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoAtualizarTabelaEx)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoRemoverTabelaEx)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(paneTabelaEpiEx, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoRemoverTabelaEx)
                    .addComponent(botaoAtualizarTabelaEx))
                .addContainerGap())
        );

        botaoSalvarEx.setText("Salvar");
        botaoSalvarEx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoSalvarExMouseClicked(evt);
            }
        });

        botaoCancelarEx.setText("Cancelar");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Exceção de Uso  EPI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoSalvarEx)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoCancelarEx)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvarEx)
                    .addComponent(botaoCancelarEx))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultaEpiExKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ConsultaEpiExKeyReleased
    controller.consultarEpiEx();
    }//GEN-LAST:event_ConsultaEpiExKeyReleased

    private void tabelaEpiExMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaEpiExMouseClicked
       
    }//GEN-LAST:event_tabelaEpiExMouseClicked

    private void botaoAdicionarExMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAdicionarExMouseClicked
         try {
             controller.inserirEpiEx();
         } catch (SQLException ex) {
             Logger.getLogger(cadastroExcecaoEPI.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_botaoAdicionarExMouseClicked

    private void consultaFuncionarioExKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_consultaFuncionarioExKeyReleased
       controller.consultarFuncionarioEx();
    }//GEN-LAST:event_consultaFuncionarioExKeyReleased

    private void tabelaConsultaExMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaConsultaExMouseClicked
        controller.preencherDadosFuncionario();
    }//GEN-LAST:event_tabelaConsultaExMouseClicked

    private void botaoAtualizarTabelaExMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAtualizarTabelaExMouseClicked
        controller.atualizarEpiExc();
    }//GEN-LAST:event_botaoAtualizarTabelaExMouseClicked

    private void botaoRemoverTabelaExMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoRemoverTabelaExMouseClicked
        controller.excluirEpiEx();
    }//GEN-LAST:event_botaoRemoverTabelaExMouseClicked

    private void botaoSalvarExMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSalvarExMouseClicked
         try {
             controller.inserirEpiExBanco();
         } catch (SQLException ex) {
             Logger.getLogger(cadastroExcecaoEPI.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_botaoSalvarExMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroExcecaoEPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroExcecaoEPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroExcecaoEPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroExcecaoEPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroExcecaoEPI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ConsultaEpiEx;
    private javax.swing.JTable TabelaEpiSetorEx;
    private javax.swing.JButton botaoAdicionarEx;
    private javax.swing.JButton botaoAtualizarTabelaEx;
    private javax.swing.JButton botaoCancelarEx;
    private javax.swing.JButton botaoRemoverTabelaEx;
    private javax.swing.JButton botaoSalvarEx;
    private javax.swing.JTextField chapaFuncionarioEx;
    private javax.swing.JTextField codFuncionarioEx;
    private javax.swing.JTextField consultaFuncionarioEx;
    private javax.swing.JTextField cpfFuncionarioEx;
    private javax.swing.JTextField dataAdmissaoEx;
    private javax.swing.JTextField empresaFuncionarioEx;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField nomeFuncionarioEx;
    private javax.swing.JTextField nomeSetorFuncEx;
    private javax.swing.JTextArea observacaoFuncionarioEx;
    private javax.swing.JTextField ocultoIdEmpresaFuncionario;
    private javax.swing.JTextField ocultoIdEpi;
    private javax.swing.JTextField ocultoSetorIdEx;
    private javax.swing.JScrollPane paneEpíEx;
    private javax.swing.JScrollPane paneTabelaConsultaEx;
    private javax.swing.JScrollPane paneTabelaEpiEx;
    private javax.swing.JScrollPane paneTabelaEpiSetorEx;
    private javax.swing.JTextField qtdEpiEx;
    private javax.swing.JTextField rgFuncionarioEx;
    private javax.swing.JTextArea riscosetorEx;
    private javax.swing.JTable tabelaConsultaEx;
    private javax.swing.JTable tabelaEpiEx;
    private javax.swing.JTable tabelaEpiSetorFuncionarioEx;
    // End of variables declaration//GEN-END:variables

    public JTextField getConsultaEpiEx() {
        return ConsultaEpiEx;
    }

    public void setConsultaEpiEx(JTextField ConsultaEpiEx) {
        this.ConsultaEpiEx = ConsultaEpiEx;
    }

    public JTable getTabelaEpiSetorEx() {
        return TabelaEpiSetorEx;
    }

    public void setTabelaEpiSetorEx(JTable TabelaEpiSetorEx) {
        this.TabelaEpiSetorEx = TabelaEpiSetorEx;
    }

    public JTextField getChapaFuncionarioEx() {
        return chapaFuncionarioEx;
    }

    public void setChapaFuncionarioEx(JTextField chapaFuncionarioEx) {
        this.chapaFuncionarioEx = chapaFuncionarioEx;
    }

    public JTextField getCodFuncionarioEx() {
        return codFuncionarioEx;
    }

    public void setCodFuncionarioEx(JTextField codFuncionarioEx) {
        this.codFuncionarioEx = codFuncionarioEx;
    }

    public JTextField getConsultaFuncionarioEx() {
        return consultaFuncionarioEx;
    }

    public void setConsultaFuncionarioEx(JTextField consultaFuncionarioEx) {
        this.consultaFuncionarioEx = consultaFuncionarioEx;
    }

    public JTextField getCpfFuncionarioEx() {
        return cpfFuncionarioEx;
    }

    public void setCpfFuncionarioEx(JTextField cpfFuncionarioEx) {
        this.cpfFuncionarioEx = cpfFuncionarioEx;
    }

    public JTextField getDataAdmissaoEx() {
        return dataAdmissaoEx;
    }

    public void setDataAdmissaoEx(JTextField dataAdmissaoEx) {
        this.dataAdmissaoEx = dataAdmissaoEx;
    }

    public JTextField getEmpresaFuncionarioEx() {
        return empresaFuncionarioEx;
    }

    public void setEmpresaFuncionarioEx(JTextField empresaFuncionarioEx) {
        this.empresaFuncionarioEx = empresaFuncionarioEx;
    }

    public JTextField getNomeFuncionarioEx() {
        return nomeFuncionarioEx;
    }

    public void setNomeFuncionarioEx(JTextField nomeFuncionarioEx) {
        this.nomeFuncionarioEx = nomeFuncionarioEx;
    }

    public JTextArea getObservacaoFuncionarioEx() {
        return observacaoFuncionarioEx;
    }

    public void setObservacaoFuncionarioEx(JTextArea observacaoFuncionarioEx) {
        this.observacaoFuncionarioEx = observacaoFuncionarioEx;
    }

    public JTextField getOcultoIdEpi() {
        return ocultoIdEpi;
    }

    public void setOcultoIdEpi(JTextField ocultoIdEpi) {
        this.ocultoIdEpi = ocultoIdEpi;
    }

    public JTextField getQtdEpiEx() {
        return qtdEpiEx;
    }

    public void setQtdEpiEx(JTextField qtdEpiEx) {
        this.qtdEpiEx = qtdEpiEx;
    }

    public JTextField getRgFuncionarioEx() {
        return rgFuncionarioEx;
    }

    public void setRgFuncionarioEx(JTextField rgFuncionarioEx) {
        this.rgFuncionarioEx = rgFuncionarioEx;
    }


    public JTable getTabelaConsultaEx() {
        return tabelaConsultaEx;
    }

    public void setTabelaConsultaEx(JTable tabelaConsultaEx) {
        this.tabelaConsultaEx = tabelaConsultaEx;
    }

    public JTable getTabelaEpiEx() {
        return tabelaEpiEx;
    }

    public void setTabelaEpiEx(JTable tabelaEpiEx) {
        this.tabelaEpiEx = tabelaEpiEx;
    }

    public JTable getTabelaEpiSetorFuncionarioEx() {
        return tabelaEpiSetorFuncionarioEx;
    }

    public void setTabelaEpiSetorFuncionarioEx(JTable tabelaEpiSetorFuncionarioEx) {
        this.tabelaEpiSetorFuncionarioEx = tabelaEpiSetorFuncionarioEx;
    }

    public JScrollPane getPaneEpíEx() {
        return paneEpíEx;
    }

    public void setPaneEpíEx(JScrollPane paneEpíEx) {
        this.paneEpíEx = paneEpíEx;
    }

    public JScrollPane getPaneTabelaEpiEx() {
        return paneTabelaEpiEx;
    }

    public void setPaneTabelaEpiEx(JScrollPane paneTabelaEpiEx) {
        this.paneTabelaEpiEx = paneTabelaEpiEx;
    }

    public JScrollPane getPaneTabelaEpiSetorEx() {
        return paneTabelaEpiSetorEx;
    }

    public void setPaneTabelaEpiSetorEx(JScrollPane paneTabelaEpiSetorEx) {
        this.paneTabelaEpiSetorEx = paneTabelaEpiSetorEx;
    }

    public JScrollPane getPaneTabelaConsultaEx() {
        return paneTabelaConsultaEx;
    }

    public void setPaneTabelaConsultaEx(JScrollPane paneTabelaConsultaEx) {
        this.paneTabelaConsultaEx = paneTabelaConsultaEx;
    }

    public JTextField getOcultoIdEmpresaFuncionario() {
        return ocultoIdEmpresaFuncionario;
    }

    public void setOcultoIdEmpresaFuncionario(JTextField ocultoIdEmpresaFuncionario) {
        this.ocultoIdEmpresaFuncionario = ocultoIdEmpresaFuncionario;
    }

    public JButton getBotaoAdicionarEx() {
        return botaoAdicionarEx;
    }

    public void setBotaoAdicionarEx(JButton botaoAdicionarEx) {
        this.botaoAdicionarEx = botaoAdicionarEx;
    }

    public JTextField getOcultoSetorIdEx() {
        return ocultoSetorIdEx;
    }

    public void setOcultoSetorIdEx(JTextField ocultoSetorIdEx) {
        this.ocultoSetorIdEx = ocultoSetorIdEx;
    }

    public JTextField getNomeSetorFuncEx() {
        return nomeSetorFuncEx;
    }

    public void setNomeSetorFuncEx(JTextField nomeSetorFuncEx) {
        this.nomeSetorFuncEx = nomeSetorFuncEx;
    }

    public JTextArea getRiscosetorEx() {
        return riscosetorEx;
    }

    public void setRiscosetorEx(JTextArea riscosetorEx) {
        this.riscosetorEx = riscosetorEx;
    }



}
