/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.conexaoBancoController;
import Model.DAO.usuarioDAO;
import Model.usuario;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabinhu
 */
public class menuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public menuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmiCadastroEPI = new javax.swing.JMenuItem();
        jmCadastroFuncionario = new javax.swing.JMenuItem();
        jmCadastroEmpresa = new javax.swing.JMenuItem();
        jmCadastroUsuario = new javax.swing.JMenuItem();
        jmOperacao = new javax.swing.JMenu();
        jmOpercaoEntregaEPI = new javax.swing.JMenuItem();
        jmOperacaoAjusteEstoque = new javax.swing.JMenuItem();
        jmOperacaoAgendaEntregaEPI = new javax.swing.JMenuItem();
        jmRelatorio = new javax.swing.JMenu();
        jmRelatorioEstoque = new javax.swing.JMenuItem();
        jmRelatorioEntregasEpi = new javax.swing.JMenu();
        jmRelatorioentregasAgendadas = new javax.swing.JMenuItem();
        jmImportacao = new javax.swing.JMenu();
        jmmImportacaoEstoque = new javax.swing.JMenuItem();
        jmImportacaoEntregaEPI = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenu();
        MenuTesteFuncoes = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AlmoxarifadoExpress");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));
        jDesktopPane1.getAccessibleContext().setAccessibleName("");
        jDesktopPane1.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setText("Data e Hora");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 810, 560, 30));

        jLabel2.setText("Usuario Logado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 806, 560, 30));

        jmCadastro.setText("Cadastro");
        jmCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroActionPerformed(evt);
            }
        });

        jmiCadastroEPI.setText("EPI");
        jmiCadastroEPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastroEPIActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiCadastroEPI);

        jmCadastroFuncionario.setText("Funcionario");
        jmCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroFuncionarioActionPerformed(evt);
            }
        });
        jmCadastro.add(jmCadastroFuncionario);

        jmCadastroEmpresa.setText("Empresa");
        jmCadastroEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmCadastroEmpresaMouseClicked(evt);
            }
        });
        jmCadastroEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroEmpresaActionPerformed(evt);
            }
        });
        jmCadastro.add(jmCadastroEmpresa);

        jmCadastroUsuario.setText("Usuario Sistema");
        jmCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroUsuarioActionPerformed(evt);
            }
        });
        jmCadastro.add(jmCadastroUsuario);

        jMenuBar1.add(jmCadastro);

        jmOperacao.setText("Operação");

        jmOpercaoEntregaEPI.setText("Entrega de EPI");
        jmOperacao.add(jmOpercaoEntregaEPI);

        jmOperacaoAjusteEstoque.setText("Ajuste de Estoque");
        jmOperacao.add(jmOperacaoAjusteEstoque);

        jmOperacaoAgendaEntregaEPI.setText("Agenda de Entrega EPI");
        jmOperacao.add(jmOperacaoAgendaEntregaEPI);

        jMenuBar1.add(jmOperacao);

        jmRelatorio.setText("Relatórios");

        jmRelatorioEstoque.setText("Relatório Estoque EPI");
        jmRelatorio.add(jmRelatorioEstoque);

        jmRelatorioEntregasEpi.setText("Relatório Entrega de EPI");
        jmRelatorio.add(jmRelatorioEntregasEpi);

        jmRelatorioentregasAgendadas.setText("Relatório Entregas Agendadas");
        jmRelatorio.add(jmRelatorioentregasAgendadas);

        jMenuBar1.add(jmRelatorio);

        jmImportacao.setText("Importações");

        jmmImportacaoEstoque.setText("Importação de Entrada de EPI");
        jmImportacao.add(jmmImportacaoEstoque);

        jmImportacaoEntregaEPI.setText("Importação de Etrega de EPI");
        jmImportacao.add(jmImportacaoEntregaEPI);

        jMenuBar1.add(jmImportacao);

        jmSair.setText("Sair");
        jmSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSairMouseClicked(evt);
            }
        });
        jmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmSair);

        MenuTesteFuncoes.setText("Menu de Testes");

        jMenuItem1.setText("Testando alterações");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuTesteFuncoes.add(jMenuItem1);

        jMenuBar1.add(MenuTesteFuncoes);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1216, 839));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //getContentPane().add(jDesktopPane);
    
    private void jmiCadastroEPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastroEPIActionPerformed
        View.Relatorios.relatorioEpi epi = new View.Relatorios.relatorioEpi();
        epi.setVisible(true);
    }//GEN-LAST:event_jmiCadastroEPIActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try{
        Connection conexaoBanco = new conexaoBancoController().conectarBanco();
        usuarioDAO usuarioCadastro = new usuarioDAO(conexaoBanco);
        
        //Testabdi Inserir
        usuario inserirUsuario = new usuario("fabiano","fabimenu"," fabimenusenha","fabiemailemail.com.br", 0);
        usuario usuarioInseridoEmBanco = usuarioCadastro.salvarUsuario(inserirUsuario);
        
        //Testando Select por ID
        usuario usuarioSelecionadoNoInsert = usuarioCadastro.consultaPorId(usuarioInseridoEmBanco);
        
        //Testando Deleção
        usuarioCadastro.excluirUsuario(usuarioSelecionadoNoInsert);
        
        
            //selecionando todos
            ArrayList<usuario> selecionarTodosUsuarios = usuarioCadastro.selecionarTodos();
        
            for (usuario selecionar : selecionarTodosUsuarios) {
                System.out.println(selecionar.getId()+" | "+selecionar.getNome());
            }
                
        }catch(SQLException ex){
            System.out.println("Erro: "+ex);
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSairMouseClicked
        Connection conexaoBanco = (Connection) new conexaoBancoController();
        try {
            conexaoBanco.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro Apresentado ao SAIR: "+ex);
        }
        System.exit(0);
        this.dispose();
    }//GEN-LAST:event_jmSairMouseClicked

    private void jmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSairActionPerformed
  
    }//GEN-LAST:event_jmSairActionPerformed

    private void jmCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroFuncionarioActionPerformed
         View.cadastroFuncionario funcionario = new View.cadastroFuncionario();
        funcionario.setVisible(true);
    }//GEN-LAST:event_jmCadastroFuncionarioActionPerformed

    private void jmCadastroEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroEmpresaActionPerformed
         View.Relatorios.relatorioEmpresa empresa = new View.Relatorios.relatorioEmpresa();
        empresa.setVisible(true);
    }//GEN-LAST:event_jmCadastroEmpresaActionPerformed

    private void jmCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroUsuarioActionPerformed
        View.Relatorios.relatorioUsuario usuario = new View.Relatorios.relatorioUsuario();
        usuario.setVisible(true);
    }//GEN-LAST:event_jmCadastroUsuarioActionPerformed

    private void jmCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmCadastroActionPerformed

    private void jmCadastroEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmCadastroEmpresaMouseClicked
        View.Relatorios.relatorioEmpresa empresa = new View.Relatorios.relatorioEmpresa();
        empresa.setVisible(true);
    }//GEN-LAST:event_jmCadastroEmpresaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuTesteFuncoes;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenuItem jmCadastroEmpresa;
    private javax.swing.JMenuItem jmCadastroFuncionario;
    private javax.swing.JMenuItem jmCadastroUsuario;
    private javax.swing.JMenu jmImportacao;
    private javax.swing.JMenuItem jmImportacaoEntregaEPI;
    private javax.swing.JMenu jmOperacao;
    private javax.swing.JMenuItem jmOperacaoAgendaEntregaEPI;
    private javax.swing.JMenuItem jmOperacaoAjusteEstoque;
    private javax.swing.JMenuItem jmOpercaoEntregaEPI;
    private javax.swing.JMenu jmRelatorio;
    private javax.swing.JMenu jmRelatorioEntregasEpi;
    private javax.swing.JMenuItem jmRelatorioEstoque;
    private javax.swing.JMenuItem jmRelatorioentregasAgendadas;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenuItem jmiCadastroEPI;
    private javax.swing.JMenuItem jmmImportacaoEstoque;
    // End of variables declaration//GEN-END:variables
}
