/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Relatorios;

import Controller.RelatorioFuncionarioController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JMenu;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Fabinhu
 */
public class intRelatorioFuncionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form intRelatorioFuncionario
     */
    
    private final RelatorioFuncionarioController controller;
    
    public intRelatorioFuncionario() {
        initComponents();
        controller = new RelatorioFuncionarioController(this);
        controller.oculatarCampos();
        controller.bloquearCamposEditar();
        getConsultaEmpresa().setText("<html>Consultra<br>Empresa</html>");
        
        paneNomeConsulta.setColumnHeader(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        nomeFuncionario = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cboSituacaoCadastro = new javax.swing.JComboBox<>();
        btnConsultar = new javax.swing.JButton();
        paneNomeConsulta = new javax.swing.JScrollPane();
        tabelaNomeConsulta = new javax.swing.JTable();
        ocultoIdFuncionario = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFuncionario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idFuncinoarioAlterar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboStatusFuncinoarioAlterar = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        observacaoFuncinoarioAlterar = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        nomeFuncinoarioAlterar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rgFuncinoarioAlterar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cpfFuncinoarioAlterar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dtAdmFuncinoarioAlterar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        chapaAlterar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        PaneSetor = new javax.swing.JScrollPane();
        tabelaConsultaSetorAlterar = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        nomeSetorFuncinoarioAlterar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        NomeempresaFuncinarioalterar = new javax.swing.JTextField();
        PaneEmpresa = new javax.swing.JScrollPane();
        tabelaConsultaEmpresaAlterar = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        idSetorOculto = new javax.swing.JTextField();
        idEmpresaoculto = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        paneConsultaEmpresa = new javax.swing.JScrollPane();
        consultaCNPJEmpresa = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        cnpjEmpresaConsulta = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        ocultoIdEmpresa = new javax.swing.JTextField();
        nomeempresaFuncionario = new javax.swing.JTextField();
        consultaEmpresa = new javax.swing.JButton();
        botaoAtualizar = new javax.swing.JButton();
        btnCancelarFuncionario = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmConsultar = new javax.swing.JMenu();
        botaoEditarMenu = new javax.swing.JMenu();
        botaoImprimir = new javax.swing.JMenu();
        botaoExcluirMenu = new javax.swing.JMenu();
        jmIncluir = new javax.swing.JMenu();

        jLabel14.setText("jLabel14");

        setClosable(true);
        setIconifiable(true);
        setTitle("Consulta de Funcionario");
        setToolTipText("Consulta, Edição Exclusão e Inclusão de Funcionarios");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel15.setText("Nome");

        nomeFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomeFuncionarioKeyReleased(evt);
            }
        });

        jLabel16.setText("Situação");

        cboSituacaoCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Excluido" }));

        btnConsultar.setText("Consulta por Funcionario");
        btnConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarMouseClicked(evt);
            }
        });

        tabelaNomeConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaNomeConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaNomeConsultaMouseClicked(evt);
            }
        });
        paneNomeConsulta.setViewportView(tabelaNomeConsulta);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(nomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ocultoIdFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneNomeConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConsultar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboSituacaoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(nomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(cboSituacaoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultar)
                    .addComponent(paneNomeConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ocultoIdFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tabelaFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaFuncionario);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar Dados Funcionario");

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Cód.");

        jLabel3.setText("Situação");

        comboStatusFuncinoarioAlterar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Excluido" }));

        jLabel4.setText("Observação");

        observacaoFuncinoarioAlterar.setColumns(20);
        observacaoFuncinoarioAlterar.setLineWrap(true);
        observacaoFuncinoarioAlterar.setRows(5);
        jScrollPane3.setViewportView(observacaoFuncinoarioAlterar);

        jLabel5.setText("Nome");

        jLabel6.setText("RG");

        jLabel7.setText("CPF");

        jLabel8.setText("DT. Adm");

        jLabel9.setText("Chapa");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Dados Setor");

        tabelaConsultaSetorAlterar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        PaneSetor.setViewportView(tabelaConsultaSetorAlterar);

        jLabel11.setText("Setor");

        nomeSetorFuncinoarioAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomeSetorFuncinoarioAlterarKeyReleased(evt);
            }
        });

        jLabel12.setText("Razão Social");

        NomeempresaFuncinarioalterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NomeempresaFuncinarioalterarKeyReleased(evt);
            }
        });

        tabelaConsultaEmpresaAlterar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        PaneEmpresa.setViewportView(tabelaConsultaEmpresaAlterar);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Dados Empresa");

        idEmpresaoculto.setText("jTextField1");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(nomeSetorFuncinoarioAlterar)
                                        .addGap(21, 21, 21)))
                                .addComponent(idSetorOculto, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idEmpresaoculto, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(PaneSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(PaneEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(NomeempresaFuncinarioalterar, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idFuncinoarioAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chapaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboStatusFuncinoarioAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(rgFuncinoarioAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cpfFuncinoarioAlterar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dtAdmFuncinoarioAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(nomeFuncinoarioAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idFuncinoarioAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(chapaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(comboStatusFuncinoarioAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(nomeFuncinoarioAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(rgFuncinoarioAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cpfFuncinoarioAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(dtAdmFuncinoarioAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeSetorFuncinoarioAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idSetorOculto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PaneSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomeempresaFuncinarioalterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idEmpresaoculto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PaneEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        consultaCNPJEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        paneConsultaEmpresa.setViewportView(consultaCNPJEmpresa);

        jLabel17.setText("CNPJ");

        cnpjEmpresaConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnpjEmpresaConsultaKeyReleased(evt);
            }
        });

        jLabel18.setText("Empesa");

        consultaEmpresa.setText("Consultar por Emprsa");
        consultaEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultaEmpresaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(paneConsultaEmpresa)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cnpjEmpresaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ocultoIdEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeempresaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(consultaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(cnpjEmpresaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(ocultoIdEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeempresaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(paneConsultaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(consultaEmpresa)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botaoAtualizar.setText("Atualizar Banco");
        botaoAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoAtualizarMouseClicked(evt);
            }
        });

        btnCancelarFuncionario.setText("Cancelar");
        btnCancelarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarFuncionarioMouseClicked(evt);
            }
        });

        jmConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeConsultar24px.png"))); // NOI18N
        jmConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmConsultarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmConsultar);

        botaoEditarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeEditar24px.png"))); // NOI18N
        botaoEditarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoEditarMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(botaoEditarMenu);

        botaoImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeImprimir24px.png"))); // NOI18N
        jMenuBar1.add(botaoImprimir);

        botaoExcluirMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeExcluir24px.png"))); // NOI18N
        botaoExcluirMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoExcluirMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(botaoExcluirMenu);

        jmIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeNovo24px.png"))); // NOI18N
        jmIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmIncluirMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmIncluir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(botaoAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarFuncionario)
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAtualizar)
                    .addComponent(btnCancelarFuncionario))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmConsultarMouseClicked
        
    }//GEN-LAST:event_jmConsultarMouseClicked

    private void botaoEditarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEditarMenuMouseClicked
        try {
            controller.editarFuncinoario();
            controller.habilitarCamposEditar();
        } catch (SQLException ex) {
            Logger.getLogger(intRelatorioFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoEditarMenuMouseClicked

    private void botaoExcluirMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoExcluirMenuMouseClicked
    controller.excluirFuncionario();
    }//GEN-LAST:event_botaoExcluirMenuMouseClicked

    private void jmIncluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmIncluirMouseClicked
     View.cadastroFuncionario funcionario = new View.cadastroFuncionario();
     funcionario.setVisible(true);
    }//GEN-LAST:event_jmIncluirMouseClicked

    private void nomeFuncionarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeFuncionarioKeyReleased
       controller.preencherIdOculto();
    }//GEN-LAST:event_nomeFuncionarioKeyReleased

    private void tabelaNomeConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaNomeConsultaMouseClicked
        controller.selecionarCampos();
    }//GEN-LAST:event_tabelaNomeConsultaMouseClicked

    private void btnConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseClicked
        controller.consultarNomeFuncionario();
    }//GEN-LAST:event_btnConsultarMouseClicked

    private void cnpjEmpresaConsultaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnpjEmpresaConsultaKeyReleased
        controller.consultarEmpresa();
    }//GEN-LAST:event_cnpjEmpresaConsultaKeyReleased

    private void consultaEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaEmpresaMouseClicked
        controller.consultaFuncionarioPorEmpresa();
    }//GEN-LAST:event_consultaEmpresaMouseClicked

    private void nomeSetorFuncinoarioAlterarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeSetorFuncinoarioAlterarKeyReleased
       controller.setarSetorEditar();
    }//GEN-LAST:event_nomeSetorFuncinoarioAlterarKeyReleased

    private void NomeempresaFuncinarioalterarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomeempresaFuncinarioalterarKeyReleased
        controller.setarEmpresaEditar();
    }//GEN-LAST:event_NomeempresaFuncinarioalterarKeyReleased

    private void botaoAtualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAtualizarMouseClicked
        try {
            controller.alteracamposFuncionario();
        } catch (SQLException ex) {
            Logger.getLogger(intRelatorioFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoAtualizarMouseClicked

    private void btnCancelarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarFuncionarioMouseClicked
        dispose();
        
    }//GEN-LAST:event_btnCancelarFuncionarioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NomeempresaFuncinarioalterar;
    private javax.swing.JScrollPane PaneEmpresa;
    private javax.swing.JScrollPane PaneSetor;
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JMenu botaoEditarMenu;
    private javax.swing.JMenu botaoExcluirMenu;
    private javax.swing.JMenu botaoImprimir;
    private javax.swing.JButton btnCancelarFuncionario;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JComboBox<String> cboSituacaoCadastro;
    private javax.swing.JTextField chapaAlterar;
    private javax.swing.JTextField cnpjEmpresaConsulta;
    private javax.swing.JComboBox<String> comboStatusFuncinoarioAlterar;
    private javax.swing.JTable consultaCNPJEmpresa;
    private javax.swing.JButton consultaEmpresa;
    private javax.swing.JTextField cpfFuncinoarioAlterar;
    private javax.swing.JTextField dtAdmFuncinoarioAlterar;
    private javax.swing.JTextField idEmpresaoculto;
    private javax.swing.JTextField idFuncinoarioAlterar;
    private javax.swing.JTextField idSetorOculto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenu jmConsultar;
    private javax.swing.JMenu jmIncluir;
    private javax.swing.JTextField nomeFuncinoarioAlterar;
    private javax.swing.JTextField nomeFuncionario;
    private javax.swing.JTextField nomeSetorFuncinoarioAlterar;
    private javax.swing.JTextField nomeempresaFuncionario;
    private javax.swing.JTextArea observacaoFuncinoarioAlterar;
    private javax.swing.JTextField ocultoIdEmpresa;
    private javax.swing.JTextField ocultoIdFuncionario;
    private javax.swing.JScrollPane paneConsultaEmpresa;
    private javax.swing.JScrollPane paneNomeConsulta;
    private javax.swing.JTextField rgFuncinoarioAlterar;
    private javax.swing.JTable tabelaConsultaEmpresaAlterar;
    private javax.swing.JTable tabelaConsultaSetorAlterar;
    private javax.swing.JTable tabelaFuncionario;
    private javax.swing.JTable tabelaNomeConsulta;
    // End of variables declaration//GEN-END:variables

    public JTextField getNomeempresaFuncinarioalterar() {
        return NomeempresaFuncinarioalterar;
    }

    public void setNomeempresaFuncinarioalterar(JTextField NomeempresaFuncinarioalterar) {
        this.NomeempresaFuncinarioalterar = NomeempresaFuncinarioalterar;
    }

    public JScrollPane getPaneEmpresa() {
        return PaneEmpresa;
    }

    public void setPaneEmpresa(JScrollPane PaneEmpresa) {
        this.PaneEmpresa = PaneEmpresa;
    }

    public JScrollPane getPaneSetor() {
        return PaneSetor;
    }

    public void setPaneSetor(JScrollPane PaneSetor) {
        this.PaneSetor = PaneSetor;
    }

    public JButton getBotaoAtualizar() {
        return botaoAtualizar;
    }

    public void setBotaoAtualizar(JButton botaoAtualizar) {
        this.botaoAtualizar = botaoAtualizar;
    }

    public JMenu getBotaoEditarMenu() {
        return botaoEditarMenu;
    }

    public void setBotaoEditarMenu(JMenu botaoEditarMenu) {
        this.botaoEditarMenu = botaoEditarMenu;
    }

    public JMenu getBotaoExcluirMenu() {
        return botaoExcluirMenu;
    }

    public void setBotaoExcluirMenu(JMenu botaoExcluirMenu) {
        this.botaoExcluirMenu = botaoExcluirMenu;
    }

    public JMenu getBotaoImprimir() {
        return botaoImprimir;
    }

    public void setBotaoImprimir(JMenu botaoImprimir) {
        this.botaoImprimir = botaoImprimir;
    }

    public JButton getBtnCancelarFuncionario() {
        return btnCancelarFuncionario;
    }

    public void setBtnCancelarFuncionario(JButton btnCancelarFuncionario) {
        this.btnCancelarFuncionario = btnCancelarFuncionario;
    }

    public JButton getBtnConsultar() {
        return btnConsultar;
    }

    public void setBtnConsultar(JButton btnConsultar) {
        this.btnConsultar = btnConsultar;
    }

    public JComboBox<String> getCboSituacaoCadastro() {
        return cboSituacaoCadastro;
    }

    public void setCboSituacaoCadastro(JComboBox<String> cboSituacaoCadastro) {
        this.cboSituacaoCadastro = cboSituacaoCadastro;
    }

    public JTextField getChapaAlterar() {
        return chapaAlterar;
    }

    public void setChapaAlterar(JTextField chapaAlterar) {
        this.chapaAlterar = chapaAlterar;
    }

    public JTextField getCnpjEmpresaConsulta() {
        return cnpjEmpresaConsulta;
    }

    public void setCnpjEmpresaConsulta(JTextField cnpjEmpresaConsulta) {
        this.cnpjEmpresaConsulta = cnpjEmpresaConsulta;
    }

    public JComboBox<String> getComboStatusFuncinoarioAlterar() {
        return comboStatusFuncinoarioAlterar;
    }

    public void setComboStatusFuncinoarioAlterar(JComboBox<String> comboStatusFuncinoarioAlterar) {
        this.comboStatusFuncinoarioAlterar = comboStatusFuncinoarioAlterar;
    }

    public JTable getConsultaCNPJEmpresa() {
        return consultaCNPJEmpresa;
    }

    public void setConsultaCNPJEmpresa(JTable consultaCNPJEmpresa) {
        this.consultaCNPJEmpresa = consultaCNPJEmpresa;
    }

    public JButton getConsultaEmpresa() {
        return consultaEmpresa;
    }

    public void setConsultaEmpresa(JButton consultaEmpresa) {
        this.consultaEmpresa = consultaEmpresa;
    }

    public JTextField getCpfFuncinoarioAlterar() {
        return cpfFuncinoarioAlterar;
    }

    public void setCpfFuncinoarioAlterar(JTextField cpfFuncinoarioAlterar) {
        this.cpfFuncinoarioAlterar = cpfFuncinoarioAlterar;
    }

    public JTextField getDtAdmFuncinoarioAlterar() {
        return dtAdmFuncinoarioAlterar;
    }

    public void setDtAdmFuncinoarioAlterar(JTextField dtAdmFuncinoarioAlterar) {
        this.dtAdmFuncinoarioAlterar = dtAdmFuncinoarioAlterar;
    }

    public JTextField getIdEmpresaoculto() {
        return idEmpresaoculto;
    }

    public void setIdEmpresaoculto(JTextField idEmpresaoculto) {
        this.idEmpresaoculto = idEmpresaoculto;
    }

    public JTextField getIdFuncinoarioAlterar() {
        return idFuncinoarioAlterar;
    }

    public void setIdFuncinoarioAlterar(JTextField idFuncinoarioAlterar) {
        this.idFuncinoarioAlterar = idFuncinoarioAlterar;
    }

    public JTextField getIdSetorOculto() {
        return idSetorOculto;
    }

    public void setIdSetorOculto(JTextField idSetorOculto) {
        this.idSetorOculto = idSetorOculto;
    }

    public JMenu getJmConsultar() {
        return jmConsultar;
    }

    public void setJmConsultar(JMenu jmConsultar) {
        this.jmConsultar = jmConsultar;
    }

    public JMenu getJmIncluir() {
        return jmIncluir;
    }

    public void setJmIncluir(JMenu jmIncluir) {
        this.jmIncluir = jmIncluir;
    }

    public JTextField getNomeFuncinoarioAlterar() {
        return nomeFuncinoarioAlterar;
    }

    public void setNomeFuncinoarioAlterar(JTextField nomeFuncinoarioAlterar) {
        this.nomeFuncinoarioAlterar = nomeFuncinoarioAlterar;
    }

    public JTextField getNomeFuncionario() {
        return nomeFuncionario;
    }

    public void setNomeFuncionario(JTextField nomeFuncionario) {
        this.nomeFuncionario = nomeFuncionario;
    }

    public JTextField getNomeSetorFuncinoarioAlterar() {
        return nomeSetorFuncinoarioAlterar;
    }

    public void setNomeSetorFuncinoarioAlterar(JTextField nomeSetorFuncinoarioAlterar) {
        this.nomeSetorFuncinoarioAlterar = nomeSetorFuncinoarioAlterar;
    }

    public JTextField getNomeempresaFuncionario() {
        return nomeempresaFuncionario;
    }

    public void setNomeempresaFuncionario(JTextField nomeempresaFuncionario) {
        this.nomeempresaFuncionario = nomeempresaFuncionario;
    }

    public JTextArea getObservacaoFuncinoarioAlterar() {
        return observacaoFuncinoarioAlterar;
    }

    public void setObservacaoFuncinoarioAlterar(JTextArea observacaoFuncinoarioAlterar) {
        this.observacaoFuncinoarioAlterar = observacaoFuncinoarioAlterar;
    }

    public JTextField getOcultoIdEmpresa() {
        return ocultoIdEmpresa;
    }

    public void setOcultoIdEmpresa(JTextField ocultoIdEmpresa) {
        this.ocultoIdEmpresa = ocultoIdEmpresa;
    }

    public JTextField getOcultoIdFuncionario() {
        return ocultoIdFuncionario;
    }

    public void setOcultoIdFuncionario(JTextField ocultoIdFuncionario) {
        this.ocultoIdFuncionario = ocultoIdFuncionario;
    }

    public JScrollPane getPaneConsultaEmpresa() {
        return paneConsultaEmpresa;
    }

    public void setPaneConsultaEmpresa(JScrollPane paneConsultaEmpresa) {
        this.paneConsultaEmpresa = paneConsultaEmpresa;
    }

    public JScrollPane getPaneNomeConsulta() {
        return paneNomeConsulta;
    }

    public void setPaneNomeConsulta(JScrollPane paneNomeConsulta) {
        this.paneNomeConsulta = paneNomeConsulta;
    }

    public JTextField getRgFuncinoarioAlterar() {
        return rgFuncinoarioAlterar;
    }

    public void setRgFuncinoarioAlterar(JTextField rgFuncinoarioAlterar) {
        this.rgFuncinoarioAlterar = rgFuncinoarioAlterar;
    }

    public JTable getTabelaConsultaEmpresaAlterar() {
        return tabelaConsultaEmpresaAlterar;
    }

    public void setTabelaConsultaEmpresaAlterar(JTable tabelaConsultaEmpresaAlterar) {
        this.tabelaConsultaEmpresaAlterar = tabelaConsultaEmpresaAlterar;
    }

    public JTable getTabelaConsultaSetorAlterar() {
        return tabelaConsultaSetorAlterar;
    }

    public void setTabelaConsultaSetorAlterar(JTable tabelaConsultaSetorAlterar) {
        this.tabelaConsultaSetorAlterar = tabelaConsultaSetorAlterar;
    }

    public JTable getTabelaFuncionario() {
        return tabelaFuncionario;
    }

    public void setTabelaFuncionario(JTable tabelaFuncionario) {
        this.tabelaFuncionario = tabelaFuncionario;
    }

    public JTable getTabelaNomeConsulta() {
        return tabelaNomeConsulta;
    }

    public void setTabelaNomeConsulta(JTable tabelaNomeConsulta) {
        this.tabelaNomeConsulta = tabelaNomeConsulta;
    }


    
}
