/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Relatorios;

import Controller.RelatorioSetorController;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JMenu;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Fabinhu
 */
public class intRelatorioSetor extends javax.swing.JInternalFrame {

    /**
     * Creates new form intRelatorioSetor
     */
    
    private RelatorioSetorController controller;
    
    public intRelatorioSetor() {
        initComponents();
        controller = new RelatorioSetorController(this);
        controller.oculataCamposView();
        botaoconsultarmenu.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        consultarSetor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbStituacaoSetor = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaSetor = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        codigoSetorRelatorio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        descricaoSetorRelatorio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        riscoSetorRelatorio = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaEpiSetor = new javax.swing.JTable();
        botaoAtualizarCadastroSetor = new javax.swing.JButton();
        cbosituacaoSetorRelatorio = new javax.swing.JComboBox<>();
        listarEpi = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        descsetor = new javax.swing.JTextField();
        codigoSetor = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        botaoconsultarmenu = new javax.swing.JMenu();
        botaoEditar = new javax.swing.JMenu();
        botaoImprimir = new javax.swing.JMenu();
        botaoExcluir = new javax.swing.JMenu();
        botaoIncluir = new javax.swing.JMenu();

        setTitle("Relatorio de Setor");
        setToolTipText("Consulta, Edição, Exclusão e Cadastro de novos Setores");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Setor");

        consultarSetor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                consultarSetorKeyReleased(evt);
            }
        });

        jLabel2.setText("Situação");

        cbStituacaoSetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Excluido" }));

        tabelaSetor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaSetor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaSetorMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaSetor);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultarSetor)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbStituacaoSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(consultarSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cbStituacaoSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Cód.");

        jLabel4.setText("Situação");

        jLabel5.setText("Desc.");

        jLabel6.setText("Risco");

        riscoSetorRelatorio.setColumns(20);
        riscoSetorRelatorio.setLineWrap(true);
        riscoSetorRelatorio.setRows(5);
        jScrollPane2.setViewportView(riscoSetorRelatorio);

        listaEpiSetor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(listaEpiSetor);

        botaoAtualizarCadastroSetor.setText("Atualizar Setor");
        botaoAtualizarCadastroSetor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoAtualizarCadastroSetorMouseClicked(evt);
            }
        });

        cbosituacaoSetorRelatorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Excluido" }));

        listarEpi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeEPI24px_1.png"))); // NOI18N
        listarEpi.setToolTipText("Clique Aqui para Listar EPI deste Setor");
        listarEpi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listarEpiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(codigoSetorRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbosituacaoSetorRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(descricaoSetorRelatorio))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listarEpi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoAtualizarCadastroSetor, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(codigoSetorRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(cbosituacaoSetorRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(descricaoSetorRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(listarEpi)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoAtualizarCadastroSetor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });

        botaoconsultarmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeConsultar24px.png"))); // NOI18N
        botaoconsultarmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoconsultarmenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(botaoconsultarmenu);

        botaoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeEditar24px.png"))); // NOI18N
        botaoEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoEditarMouseClicked(evt);
            }
        });
        jMenuBar1.add(botaoEditar);

        botaoImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeImprimir24px.png"))); // NOI18N
        jMenuBar1.add(botaoImprimir);

        botaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeExcluir24px.png"))); // NOI18N
        botaoExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoExcluirMouseClicked(evt);
            }
        });
        jMenuBar1.add(botaoExcluir);

        botaoIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeNovo24px.png"))); // NOI18N
        botaoIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoIncluirMouseClicked(evt);
            }
        });
        jMenuBar1.add(botaoIncluir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(codigoSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descsetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnSair))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(descsetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoconsultarmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoconsultarmenuMouseClicked

    }//GEN-LAST:event_botaoconsultarmenuMouseClicked

    private void botaoEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEditarMouseClicked
     controller.preencherCamposSetor();
    }//GEN-LAST:event_botaoEditarMouseClicked

    private void botaoExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoExcluirMouseClicked
     controller.excluirSetor();
    }//GEN-LAST:event_botaoExcluirMouseClicked

    private void botaoIncluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoIncluirMouseClicked
        View.cadastroSetor setor = new View.cadastroSetor();
        setor.setVisible(true);
    }//GEN-LAST:event_botaoIncluirMouseClicked

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
      dispose();
    }//GEN-LAST:event_btnSairMouseClicked

    private void consultarSetorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_consultarSetorKeyReleased
        controller.consultarSetor();
        botaoEditar.setEnabled(true);
    }//GEN-LAST:event_consultarSetorKeyReleased

    private void tabelaSetorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaSetorMouseClicked
        controller.pegarSelecaoTabelaSetor();
    }//GEN-LAST:event_tabelaSetorMouseClicked

    private void listarEpiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarEpiMouseClicked
        controller.preencherEpiSetor();
    }//GEN-LAST:event_listarEpiMouseClicked

    private void botaoAtualizarCadastroSetorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAtualizarCadastroSetorMouseClicked
        controller.atualizarCadastroSetor();
    }//GEN-LAST:event_botaoAtualizarCadastroSetorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAtualizarCadastroSetor;
    private javax.swing.JMenu botaoEditar;
    private javax.swing.JMenu botaoExcluir;
    private javax.swing.JMenu botaoImprimir;
    private javax.swing.JMenu botaoIncluir;
    private javax.swing.JMenu botaoconsultarmenu;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbStituacaoSetor;
    private javax.swing.JComboBox<String> cbosituacaoSetorRelatorio;
    private javax.swing.JTextField codigoSetor;
    private javax.swing.JTextField codigoSetorRelatorio;
    private javax.swing.JTextField consultarSetor;
    private javax.swing.JTextField descricaoSetorRelatorio;
    private javax.swing.JTextField descsetor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable listaEpiSetor;
    private javax.swing.JButton listarEpi;
    private javax.swing.JTextArea riscoSetorRelatorio;
    private javax.swing.JTable tabelaSetor;
    // End of variables declaration//GEN-END:variables

    public JButton getBotaoAtualizarCadastroSetor() {
        return botaoAtualizarCadastroSetor;
    }

    public void setBotaoAtualizarCadastroSetor(JButton botaoAtualizarCadastroSetor) {
        this.botaoAtualizarCadastroSetor = botaoAtualizarCadastroSetor;
    }

    public JMenu getBotaoEditar() {
        return botaoEditar;
    }

    public void setBotaoEditar(JMenu botaoEditar) {
        this.botaoEditar = botaoEditar;
    }

    public JMenu getBotaoExcluir() {
        return botaoExcluir;
    }

    public void setBotaoExcluir(JMenu botaoExcluir) {
        this.botaoExcluir = botaoExcluir;
    }

    public JMenu getBotaoImprimir() {
        return botaoImprimir;
    }

    public void setBotaoImprimir(JMenu botaoImprimir) {
        this.botaoImprimir = botaoImprimir;
    }

    public JMenu getBotaoIncluir() {
        return botaoIncluir;
    }

    public void setBotaoIncluir(JMenu botaoIncluir) {
        this.botaoIncluir = botaoIncluir;
    }

    public JMenu getBotaoconsultarmenu() {
        return botaoconsultarmenu;
    }

    public void setBotaoconsultarmenu(JMenu botaoconsultarmenu) {
        this.botaoconsultarmenu = botaoconsultarmenu;
    }

    public JButton getBtnSair() {
        return btnSair;
    }

    public void setBtnSair(JButton btnSair) {
        this.btnSair = btnSair;
    }

    public JComboBox<String> getCbStituacaoSetor() {
        return cbStituacaoSetor;
    }

    public void setCbStituacaoSetor(JComboBox<String> cbStituacaoSetor) {
        this.cbStituacaoSetor = cbStituacaoSetor;
    }

    public JComboBox<String> getCbosituacaoSetorRelatorio() {
        return cbosituacaoSetorRelatorio;
    }

    public void setCbosituacaoSetorRelatorio(JComboBox<String> cbosituacaoSetorRelatorio) {
        this.cbosituacaoSetorRelatorio = cbosituacaoSetorRelatorio;
    }

    public JTextField getCodigoSetor() {
        return codigoSetor;
    }

    public void setCodigoSetor(JTextField codigoSetor) {
        this.codigoSetor = codigoSetor;
    }

    public JTextField getCodigoSetorRelatorio() {
        return codigoSetorRelatorio;
    }

    public void setCodigoSetorRelatorio(JTextField codigoSetorRelatorio) {
        this.codigoSetorRelatorio = codigoSetorRelatorio;
    }

    public JTextField getConsultarSetor() {
        return consultarSetor;
    }

    public void setConsultarSetor(JTextField consultarSetor) {
        this.consultarSetor = consultarSetor;
    }

    public JTextField getDescricaoSetorRelatorio() {
        return descricaoSetorRelatorio;
    }

    public void setDescricaoSetorRelatorio(JTextField descricaoSetorRelatorio) {
        this.descricaoSetorRelatorio = descricaoSetorRelatorio;
    }

    public JTextField getDescsetor() {
        return descsetor;
    }

    public void setDescsetor(JTextField descsetor) {
        this.descsetor = descsetor;
    }

    public JTable getListaEpiSetor() {
        return listaEpiSetor;
    }

    public void setListaEpiSetor(JTable listaEpiSetor) {
        this.listaEpiSetor = listaEpiSetor;
    }

    public JButton getListarEpi() {
        return listarEpi;
    }

    public void setListarEpi(JButton listarEpi) {
        this.listarEpi = listarEpi;
    }

    public JTextArea getRiscoSetorRelatorio() {
        return riscoSetorRelatorio;
    }

    public void setRiscoSetorRelatorio(JTextArea riscoSetorRelatorio) {
        this.riscoSetorRelatorio = riscoSetorRelatorio;
    }

    public JTable getTabelaSetor() {
        return tabelaSetor;
    }

    public void setTabelaSetor(JTable tabelaSetor) {
        this.tabelaSetor = tabelaSetor;
    }


}
