/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Relatorios;

import Controller.RelatorioSetorController;
import javax.swing.JComboBox;
import javax.swing.JMenu;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Fabinhu
 */
public class relatorioSetor extends javax.swing.JFrame {

    /**
     * Creates new form relatorioSetor
     */
    
    private RelatorioSetorController controller;
    
    public relatorioSetor() {
        initComponents();
        controller = new RelatorioSetorController(this);
        controller.oculataCamposView();
        
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelConsultaSetor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        consultarSetor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbStituacaoSetor = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaSetor = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        codigoSetor = new javax.swing.JTextField();
        painelSetor = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        codigoSetorRelatorio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        descricaoSetorRelatorio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        riscoSetorRelatorio = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        cbosituacaoSetorRelatorio = new javax.swing.JComboBox<>();
        botaoAtualizarCadastroSetor = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaEpiSetor = new javax.swing.JTable();
        listarEpi = new javax.swing.JButton();
        descsetor = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        botaoConsultar = new javax.swing.JMenu();
        botaoImprimir = new javax.swing.JMenu();
        botaoEditar = new javax.swing.JMenu();
        botaoExcluir = new javax.swing.JMenu();
        botaoIncluir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta e Edição de Setor");

        PainelConsultaSetor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Setor");

        consultarSetor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                consultarSetorKeyReleased(evt);
            }
        });

        jLabel2.setText("Situação");

        cbStituacaoSetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Excluido" }));

        tabelaSetor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaSetor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaSetorMouseClicked(evt);
            }
        });
        tabelaSetor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaSetorKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaSetor);

        javax.swing.GroupLayout PainelConsultaSetorLayout = new javax.swing.GroupLayout(PainelConsultaSetor);
        PainelConsultaSetor.setLayout(PainelConsultaSetorLayout);
        PainelConsultaSetorLayout.setHorizontalGroup(
            PainelConsultaSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConsultaSetorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelConsultaSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelConsultaSetorLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultarSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbStituacaoSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelConsultaSetorLayout.setVerticalGroup(
            PainelConsultaSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConsultaSetorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelConsultaSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultarSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cbStituacaoSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jButton2.setText("Sair");

        codigoSetor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codigoSetorKeyReleased(evt);
            }
        });

        painelSetor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Código");

        codigoSetorRelatorio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codigoSetorRelatorioKeyReleased(evt);
            }
        });

        jLabel4.setText("Descrição");

        jLabel5.setText("Risco");

        riscoSetorRelatorio.setColumns(20);
        riscoSetorRelatorio.setLineWrap(true);
        riscoSetorRelatorio.setRows(5);
        riscoSetorRelatorio.setTabSize(4);
        jScrollPane2.setViewportView(riscoSetorRelatorio);

        jLabel6.setText("Situação");

        cbosituacaoSetorRelatorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Excluido" }));

        botaoAtualizarCadastroSetor.setText("Atualizar Setor");
        botaoAtualizarCadastroSetor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoAtualizarCadastroSetorMouseClicked(evt);
            }
        });

        listaEpiSetor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EPI", "Qtd."
            }
        ));
        jScrollPane3.setViewportView(listaEpiSetor);

        listarEpi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeepi32px.png"))); // NOI18N
        listarEpi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listarEpiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelSetorLayout = new javax.swing.GroupLayout(painelSetor);
        painelSetor.setLayout(painelSetorLayout);
        painelSetorLayout.setHorizontalGroup(
            painelSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSetorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoAtualizarCadastroSetor)
                    .addGroup(painelSetorLayout.createSequentialGroup()
                        .addGroup(painelSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelSetorLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(painelSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)))
                        .addGroup(painelSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelSetorLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(codigoSetorRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbosituacaoSetorRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelSetorLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelSetorLayout.createSequentialGroup()
                                        .addComponent(descricaoSetorRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listarEpi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        painelSetorLayout.setVerticalGroup(
            painelSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSetorLayout.createSequentialGroup()
                .addGroup(painelSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelSetorLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(painelSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(codigoSetorRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(cbosituacaoSetorRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(descricaoSetorRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(painelSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelSetorLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(listarEpi))
                    .addGroup(painelSetorLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoAtualizarCadastroSetor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botaoConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeConsultar24px.png"))); // NOI18N
        jMenuBar1.add(botaoConsultar);

        botaoImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeImprimir24px.png"))); // NOI18N
        jMenuBar1.add(botaoImprimir);

        botaoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeEditar24px.png"))); // NOI18N
        botaoEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoEditarMouseClicked(evt);
            }
        });
        jMenuBar1.add(botaoEditar);

        botaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeExcluir32px.png"))); // NOI18N
        botaoExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoExcluirMouseClicked(evt);
            }
        });
        jMenuBar1.add(botaoExcluir);

        botaoIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeNovo24px.png"))); // NOI18N
        botaoIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoIncluirMouseClicked(evt);
            }
        });
        botaoIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIncluirActionPerformed(evt);
            }
        });
        jMenuBar1.add(botaoIncluir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(codigoSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descsetor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelSetor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelConsultaSetor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelConsultaSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(codigoSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descsetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
 
    private void botaoIncluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoIncluirMouseClicked
        View.cadastroSetor setor = new View.cadastroSetor();
        setor.setVisible(true);
    }//GEN-LAST:event_botaoIncluirMouseClicked

    private void botaoIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIncluirActionPerformed

    }//GEN-LAST:event_botaoIncluirActionPerformed

    private void consultarSetorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_consultarSetorKeyReleased
        controller.consultarSetor();
        botaoEditar.setEnabled(true);
    }//GEN-LAST:event_consultarSetorKeyReleased

    private void botaoEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEditarMouseClicked
 
        controller.preencherCamposSetor();
   
       
    }//GEN-LAST:event_botaoEditarMouseClicked

    private void codigoSetorRelatorioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoSetorRelatorioKeyReleased
      
    }//GEN-LAST:event_codigoSetorRelatorioKeyReleased

    private void listarEpiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarEpiMouseClicked
        controller.preencherEpiSetor();
    }//GEN-LAST:event_listarEpiMouseClicked

    private void botaoExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoExcluirMouseClicked
        controller.excluirSetor();
    }//GEN-LAST:event_botaoExcluirMouseClicked

    private void codigoSetorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoSetorKeyReleased
       
    }//GEN-LAST:event_codigoSetorKeyReleased

    private void tabelaSetorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaSetorMouseClicked
        controller.pegarSelecaoTabelaSetor();
    }//GEN-LAST:event_tabelaSetorMouseClicked

    private void tabelaSetorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaSetorKeyReleased
       
    }//GEN-LAST:event_tabelaSetorKeyReleased

    private void botaoAtualizarCadastroSetorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAtualizarCadastroSetorMouseClicked
       controller.atualizarCadastroSetor();
    }//GEN-LAST:event_botaoAtualizarCadastroSetorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(relatorioSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(relatorioSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(relatorioSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(relatorioSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new relatorioSetor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelConsultaSetor;
    private javax.swing.JButton botaoAtualizarCadastroSetor;
    private javax.swing.JMenu botaoConsultar;
    private javax.swing.JMenu botaoEditar;
    private javax.swing.JMenu botaoExcluir;
    private javax.swing.JMenu botaoImprimir;
    private javax.swing.JMenu botaoIncluir;
    private javax.swing.JComboBox<String> cbStituacaoSetor;
    private javax.swing.JComboBox<String> cbosituacaoSetorRelatorio;
    private javax.swing.JTextField codigoSetor;
    private javax.swing.JTextField codigoSetorRelatorio;
    private javax.swing.JTextField consultarSetor;
    private javax.swing.JTextField descricaoSetorRelatorio;
    private javax.swing.JTextField descsetor;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable listaEpiSetor;
    private javax.swing.JButton listarEpi;
    private javax.swing.JPanel painelSetor;
    private javax.swing.JTextArea riscoSetorRelatorio;
    private javax.swing.JTable tabelaSetor;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getCbStituacaoSetor() {
        return cbStituacaoSetor;
    }

    public void setCbStituacaoSetor(JComboBox<String> cbStituacaoSetor) {
        this.cbStituacaoSetor = cbStituacaoSetor;
    }

    public JTextField getConsultarSetor() {
        return consultarSetor;
    }

    public void setConsultarSetor(JTextField consultarSetor) {
        this.consultarSetor = consultarSetor;
    }

    public JTable getTabelaSetor() {
        return tabelaSetor;
    }

    public void setTabelaSetor(JTable tabelaSetor) {
        this.tabelaSetor = tabelaSetor;
    }

    public JTextField getCodigoSetor() {
        return codigoSetor;
    }

    public void setCodigoSetor(JTextField codigoSetor) {
        this.codigoSetor = codigoSetor;
    }

    public JTextField getCodigoSetorRelatorio() {
        return codigoSetorRelatorio;
    }

    public void setCodigoSetorRelatorio(JTextField codigoSetorRelatorio) {
        this.codigoSetorRelatorio = codigoSetorRelatorio;
    }

    public JTextField getDescricaoSetorRelatorio() {
        return descricaoSetorRelatorio;
    }

    public void setDescricaoSetorRelatorio(JTextField descricaoSetorRelatorio) {
        this.descricaoSetorRelatorio = descricaoSetorRelatorio;
    }

    public JTextArea getRiscoSetorRelatorio() {
        return riscoSetorRelatorio;
    }

    public void setRiscoSetorRelatorio(JTextArea riscoSetorRelatorio) {
        this.riscoSetorRelatorio = riscoSetorRelatorio;
    }

    public JTable getListaEpiSetor() {
        return listaEpiSetor;
    }

    public void setListaEpiSetor(JTable listaEpiSetor) {
        this.listaEpiSetor = listaEpiSetor;
    }

    public JMenu getBotaoConsultar() {
        return botaoConsultar;
    }

    public void setBotaoConsultar(JMenu botaoConsultar) {
        this.botaoConsultar = botaoConsultar;
    }

    public JMenu getBotaoEditar() {
        return botaoEditar;
    }

    public void setBotaoEditar(JMenu botaoEditar) {
        this.botaoEditar = botaoEditar;
    }

    public JMenu getBotaoExcluir() {
        return botaoExcluir;
    }

    public void setBotaoExcluir(JMenu botaoExcluir) {
        this.botaoExcluir = botaoExcluir;
    }

    public JMenu getBotaoImprimir() {
        return botaoImprimir;
    }

    public void setBotaoImprimir(JMenu botaoImprimir) {
        this.botaoImprimir = botaoImprimir;
    }

    public JMenu getBotaoIncluir() {
        return botaoIncluir;
    }

    public void setBotaoIncluir(JMenu botaoIncluir) {
        this.botaoIncluir = botaoIncluir;
    }

    public JComboBox<String> getCbosituacaoSetorRelatorio() {
        return cbosituacaoSetorRelatorio;
    }

    public void setCbosituacaoSetorRelatorio(JComboBox<String> cbosituacaoSetorRelatorio) {
        this.cbosituacaoSetorRelatorio = cbosituacaoSetorRelatorio;
    }

    public JTextField getDescsetor() {
        return descsetor;
    }

    public void setDescsetor(JTextField descsetor) {
        this.descsetor = descsetor;
    }



    
    
}
