/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Relatorios;

import Controller.RelatorioSetorEpiController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenu;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Fabinhu
 */
public class relatorioSetorEpi extends javax.swing.JFrame {

    /**
     * Creates new form relatorioSetorEpi
     */
    
     private RelatorioSetorEpiController controller;
    
    public relatorioSetorEpi() {
        initComponents();
        controller = new RelatorioSetorEpiController(this);
        /*nao mostrar o cabeçalho da tabela 
        
           Neste Exemplo, ele oculta mas fica a linha cinza
        getTabelaSetoresConsulta().getTableHeader().setVisible(false);
        
            Ja neste Exemplo, ele oculca inclusive a linha cinza
        getTabelaSetoresConsulta().getTableHeader().setUI(null);
        */
        getTabelaSetoresConsulta().getTableHeader().setUI(null);
        getBotaSALVAR().setEnabled(false);
        botaoCONSULTAR.setEnabled(false);
        consultaTelaRelatorio.setEnabled(false);
        botaoEXCLUIR.setEnabled(false);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaSetoresConsulta = new javax.swing.JTable();
        consultaSetorRelatorio = new javax.swing.JTextField();
        consultaTelaRelatorio = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        codigoSetorconsulta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nomeSetorConsulta = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaSetorEpiRelatorio = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        botaoCONSULTAR = new javax.swing.JMenu();
        botaoEXCLUIR = new javax.swing.JMenu();
        botaSALVAR = new javax.swing.JMenu();
        botaoINCLUIR = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Setor/EPI");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Setor");

        tabelaSetoresConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaSetoresConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaSetoresConsultaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaSetoresConsulta);

        consultaSetorRelatorio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                consultaSetorRelatorioKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addComponent(consultaSetorRelatorio))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(consultaSetorRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        consultaTelaRelatorio.setText("Consultar");
        consultaTelaRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultaTelaRelatorioMouseClicked(evt);
            }
        });

        jButton2.setText("Sair");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Codigo");

        jLabel3.setText("Setor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigoSetorconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeSetorConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codigoSetorconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(nomeSetorConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tabelaSetorEpiRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaSetorEpiRelatorio);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        botaoCONSULTAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeConsultar24px.png"))); // NOI18N
        botaoCONSULTAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCONSULTARMouseClicked(evt);
            }
        });
        jMenuBar1.add(botaoCONSULTAR);

        botaoEXCLUIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeExcluir32px.png"))); // NOI18N
        botaoEXCLUIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoEXCLUIRMouseClicked(evt);
            }
        });
        jMenuBar1.add(botaoEXCLUIR);

        botaSALVAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeSalvar24px.png"))); // NOI18N
        jMenuBar1.add(botaSALVAR);

        botaoINCLUIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeNovo24px.png"))); // NOI18N
        botaoINCLUIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoINCLUIRMouseClicked(evt);
            }
        });
        botaoINCLUIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoINCLUIRActionPerformed(evt);
            }
        });
        jMenuBar1.add(botaoINCLUIR);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(consultaTelaRelatorio)
                        .addGap(30, 30, 30)
                        .addComponent(jButton2)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaTelaRelatorio)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoINCLUIRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoINCLUIRMouseClicked
         try {
             View.cadastroSetorEpi cadSetorEpi = new View.cadastroSetorEpi();
             cadSetorEpi.setVisible(true);
         } catch (SQLException ex) {
             Logger.getLogger(relatorioSetorEpi.class.getName()).log(Level.SEVERE, null, ex);
         }
    
    }//GEN-LAST:event_botaoINCLUIRMouseClicked

    private void botaoINCLUIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoINCLUIRActionPerformed

    }//GEN-LAST:event_botaoINCLUIRActionPerformed

    private void botaoCONSULTARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCONSULTARMouseClicked
        controller.carregarSetorEpi();
    }//GEN-LAST:event_botaoCONSULTARMouseClicked

    private void consultaTelaRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaTelaRelatorioMouseClicked
        controller.carregarSetorEpi();
    }//GEN-LAST:event_consultaTelaRelatorioMouseClicked

    private void consultaSetorRelatorioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_consultaSetorRelatorioKeyReleased
        try {
            controller.consultarSetorRelatorio();
        } catch (Exception e) {
            System.out.println(e);
        }
 
    }//GEN-LAST:event_consultaSetorRelatorioKeyReleased

    private void tabelaSetoresConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaSetoresConsultaMouseClicked
        controller.preencherCamposSetor();
        botaoCONSULTAR.setEnabled(true);
        consultaTelaRelatorio.setEnabled(true);
        botaoEXCLUIR.setEnabled(true);
    }//GEN-LAST:event_tabelaSetoresConsultaMouseClicked

    private void botaoEXCLUIRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEXCLUIRMouseClicked
        controller.excluirSetorEPI();
    }//GEN-LAST:event_botaoEXCLUIRMouseClicked

    
     
     /*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      /*  try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(relatorioSetorEpi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(relatorioSetorEpi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(relatorioSetorEpi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(relatorioSetorEpi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       /* /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new relatorioSetorEpi().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu botaSALVAR;
    private javax.swing.JMenu botaoCONSULTAR;
    private javax.swing.JMenu botaoEXCLUIR;
    private javax.swing.JMenu botaoINCLUIR;
    private javax.swing.JTextField codigoSetorconsulta;
    private javax.swing.JTextField consultaSetorRelatorio;
    private javax.swing.JButton consultaTelaRelatorio;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nomeSetorConsulta;
    private javax.swing.JTable tabelaSetorEpiRelatorio;
    private javax.swing.JTable tabelaSetoresConsulta;
    // End of variables declaration//GEN-END:variables

    public JMenu getBotaSALVAR() {
        return botaSALVAR;
    }

    public void setBotaSALVAR(JMenu botaSALVAR) {
        this.botaSALVAR = botaSALVAR;
    }

    public JTable getTabelaSetoresConsulta() {
        return tabelaSetoresConsulta;
    }

    public void setTabelaSetoresConsulta(JTable tabelaSetoresConsulta) {
        this.tabelaSetoresConsulta = tabelaSetoresConsulta;
    }

    public JTextField getConsultaSetorRelatorio() {
        return consultaSetorRelatorio;
    }

    public void setConsultaSetorRelatorio(JTextField consultaSetorRelatorio) {
        this.consultaSetorRelatorio = consultaSetorRelatorio;
    }

    public JTextField getCodigoSetorconsulta() {
        return codigoSetorconsulta;
    }

    public void setCodigoSetorconsulta(JTextField codigoSetorconsulta) {
        this.codigoSetorconsulta = codigoSetorconsulta;
    }

    public JTextField getNomeSetorConsulta() {
        return nomeSetorConsulta;
    }

    public void setNomeSetorConsulta(JTextField nomeSetorConsulta) {
        this.nomeSetorConsulta = nomeSetorConsulta;
    }

    public JTable getTabelaSetorEpiRelatorio() {
        return tabelaSetorEpiRelatorio;
    }

    public void setTabelaSetorEpiRelatorio(JTable tabelaSetorEpiRelatorio) {
        this.tabelaSetorEpiRelatorio = tabelaSetorEpiRelatorio;
    }

   
    
}
