/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Relatorios;

import Controller.RelatorioExcecaoEpiController;
import javax.swing.JButton;
import javax.swing.JMenu;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Fabinhu
 */
public class relatorioExcecaoEpi extends javax.swing.JFrame {

    /**
     * Creates new form relatorioExcecaoEpi
     */
    
      private RelatorioExcecaoEpiController controller;
      
    public relatorioExcecaoEpi() {
        initComponents();
        controller = new RelatorioExcecaoEpiController(this);
        controller.ocultarCamposEx();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        consultaExFuncionario = new javax.swing.JTextField();
        paneConsultaExFuncionario = new javax.swing.JScrollPane();
        tabelaConsultaExFuncionario = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomeFuncEx = new javax.swing.JTextField();
        chapaFuncEx = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cpfFuncEx = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        setorNomeFuncEx = new javax.swing.JTextField();
        setoridFuncEx = new javax.swing.JTextField();
        codigoFuncionarioEx = new javax.swing.JTextField();
        ocultoIdEmpresa = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        PaneResultadoEx = new javax.swing.JScrollPane();
        TabelaResultadoEx = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        botaoConsultarEx = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        botaoConsultar = new javax.swing.JMenu();
        botaoImprimir = new javax.swing.JMenu();
        botaoExcluirMenu = new javax.swing.JMenu();
        botaoEditar = new javax.swing.JMenu();
        botaoIncluir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatorio de Consulta de Exceção de EPI");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Funcionario");

        consultaExFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                consultaExFuncionarioKeyReleased(evt);
            }
        });

        tabelaConsultaExFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaConsultaExFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaConsultaExFuncionarioMouseClicked(evt);
            }
        });
        tabelaConsultaExFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaConsultaExFuncionarioKeyReleased(evt);
            }
        });
        paneConsultaExFuncionario.setViewportView(tabelaConsultaExFuncionario);

        jLabel2.setText("Nome");

        jLabel3.setText("Chapa");

        nomeFuncEx.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                nomeFuncExPropertyChange(evt);
            }
        });
        nomeFuncEx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomeFuncExKeyReleased(evt);
            }
        });

        jLabel4.setText("CPF");

        jLabel5.setText("Setor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chapaFuncEx, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setorNomeFuncEx, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeFuncEx, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4)
                                .addGap(74, 74, 74))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(ocultoIdEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(paneConsultaExFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                                    .addComponent(consultaExFuncionario))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoFuncionarioEx, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setoridFuncEx, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cpfFuncEx, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(consultaExFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(paneConsultaExFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(ocultoIdEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(codigoFuncionarioEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setoridFuncEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeFuncEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cpfFuncEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(chapaFuncEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(setorNomeFuncEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TabelaResultadoEx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        PaneResultadoEx.setViewportView(TabelaResultadoEx);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(PaneResultadoEx)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(PaneResultadoEx, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton1.setText("Sair");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        botaoConsultarEx.setText("Consultar");
        botaoConsultarEx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoConsultarExMouseClicked(evt);
            }
        });

        botaoConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeConsultar24px.png"))); // NOI18N
        jMenuBar1.add(botaoConsultar);

        botaoImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeImprimir24px.png"))); // NOI18N
        jMenuBar1.add(botaoImprimir);

        botaoExcluirMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeExcluir32px.png"))); // NOI18N
        botaoExcluirMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoExcluirMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(botaoExcluirMenu);

        botaoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeEditar24px.png"))); // NOI18N
        botaoEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoEditarMouseClicked(evt);
            }
        });
        jMenuBar1.add(botaoEditar);

        botaoIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/iconeNovo24px.png"))); // NOI18N
        botaoIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoIncluirMouseClicked(evt);
            }
        });
        botaoIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIncluirActionPerformed(evt);
            }
        });
        jMenuBar1.add(botaoIncluir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoConsultarEx)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(botaoConsultarEx))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEditarMouseClicked
       View.cadastroExcecaoEPI cadEx = new View.cadastroExcecaoEPI();
        cadEx.setVisible(true);
    }//GEN-LAST:event_botaoEditarMouseClicked

    private void botaoIncluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoIncluirMouseClicked
    View.cadastroExcecaoEPI cadEx = new View.cadastroExcecaoEPI();
    cadEx.setVisible(true);
    }//GEN-LAST:event_botaoIncluirMouseClicked

    private void botaoIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIncluirActionPerformed

    }//GEN-LAST:event_botaoIncluirActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked

    private void tabelaConsultaExFuncionarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaConsultaExFuncionarioKeyReleased
       
    }//GEN-LAST:event_tabelaConsultaExFuncionarioKeyReleased

    private void consultaExFuncionarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_consultaExFuncionarioKeyReleased
        controller.consultarFuncionarioEx();
    }//GEN-LAST:event_consultaExFuncionarioKeyReleased

    private void tabelaConsultaExFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaConsultaExFuncionarioMouseClicked
        controller.preencherDadosFuncionario();
        getBotaoExcluirMenu().setEnabled(true);
    }//GEN-LAST:event_tabelaConsultaExFuncionarioMouseClicked

    private void nomeFuncExKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeFuncExKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFuncExKeyReleased

    private void nomeFuncExPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_nomeFuncExPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFuncExPropertyChange

    private void botaoConsultarExMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConsultarExMouseClicked
       controller.preencherExcecaoEPI();
       getBotaoImprimir().setEnabled(true);
    }//GEN-LAST:event_botaoConsultarExMouseClicked

    private void botaoExcluirMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoExcluirMenuMouseClicked
       controller.excluirEPISetorEx();
    }//GEN-LAST:event_botaoExcluirMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(relatorioExcecaoEpi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(relatorioExcecaoEpi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(relatorioExcecaoEpi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(relatorioExcecaoEpi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new relatorioExcecaoEpi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane PaneResultadoEx;
    private javax.swing.JTable TabelaResultadoEx;
    private javax.swing.JMenu botaoConsultar;
    private javax.swing.JButton botaoConsultarEx;
    private javax.swing.JMenu botaoEditar;
    private javax.swing.JMenu botaoExcluirMenu;
    private javax.swing.JMenu botaoImprimir;
    private javax.swing.JMenu botaoIncluir;
    private javax.swing.JTextField chapaFuncEx;
    private javax.swing.JTextField codigoFuncionarioEx;
    private javax.swing.JTextField consultaExFuncionario;
    private javax.swing.JTextField cpfFuncEx;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nomeFuncEx;
    private javax.swing.JTextField ocultoIdEmpresa;
    private javax.swing.JScrollPane paneConsultaExFuncionario;
    private javax.swing.JTextField setorNomeFuncEx;
    private javax.swing.JTextField setoridFuncEx;
    private javax.swing.JTable tabelaConsultaExFuncionario;
    // End of variables declaration//GEN-END:variables

    public JScrollPane getPaneResultadoEx() {
        return PaneResultadoEx;
    }

    public void setPaneResultadoEx(JScrollPane PaneResultadoEx) {
        this.PaneResultadoEx = PaneResultadoEx;
    }

    public JTable getTabelaResultadoEx() {
        return TabelaResultadoEx;
    }

    public void setTabelaResultadoEx(JTable TabelaResultadoEx) {
        this.TabelaResultadoEx = TabelaResultadoEx;
    }

    public JTextField getChapaFuncEx() {
        return chapaFuncEx;
    }

    public void setChapaFuncEx(JTextField chapaFuncEx) {
        this.chapaFuncEx = chapaFuncEx;
    }

    public JTextField getConsultaExFuncionario() {
        return consultaExFuncionario;
    }

    public void setConsultaExFuncionario(JTextField consultaExFuncionario) {
        this.consultaExFuncionario = consultaExFuncionario;
    }

    public JTextField getCpfFuncEx() {
        return cpfFuncEx;
    }

    public void setCpfFuncEx(JTextField cpfFuncEx) {
        this.cpfFuncEx = cpfFuncEx;
    }

    public JTextField getNomeFuncEx() {
        return nomeFuncEx;
    }

    public void setNomeFuncEx(JTextField nomeFuncEx) {
        this.nomeFuncEx = nomeFuncEx;
    }

    public JScrollPane getPaneConsultaExFuncionario() {
        return paneConsultaExFuncionario;
    }

    public void setPaneConsultaExFuncionario(JScrollPane paneConsultaExFuncionario) {
        this.paneConsultaExFuncionario = paneConsultaExFuncionario;
    }

    public JTextField getSetoridFuncEx() {
        return setoridFuncEx;
    }

    public void setSetoridFuncEx(JTextField setoridFuncEx) {
        this.setoridFuncEx = setoridFuncEx;
    }

    public JTable getTabelaConsultaExFuncionario() {
        return tabelaConsultaExFuncionario;
    }

    public void setTabelaConsultaExFuncionario(JTable tabelaConsultaExFuncionario) {
        this.tabelaConsultaExFuncionario = tabelaConsultaExFuncionario;
    }

    public JTextField getSetorNomeFuncEx() {
        return setorNomeFuncEx;
    }

    public void setSetorNomeFuncEx(JTextField setorNomeFuncEx) {
        this.setorNomeFuncEx = setorNomeFuncEx;
    }

    public JTextField getCodigoFuncionarioEx() {
        return codigoFuncionarioEx;
    }

    public void setCodigoFuncionarioEx(JTextField codigoFuncionarioEx) {
        this.codigoFuncionarioEx = codigoFuncionarioEx;
    }

    public JTextField getOcultoIdEmpresa() {
        return ocultoIdEmpresa;
    }

    public void setOcultoIdEmpresa(JTextField ocultoIdEmpresa) {
        this.ocultoIdEmpresa = ocultoIdEmpresa;
    }

    public JMenu getBotaoConsultar() {
        return botaoConsultar;
    }

    public void setBotaoConsultar(JMenu botaoConsultar) {
        this.botaoConsultar = botaoConsultar;
    }

    public JButton getBotaoConsultarEx() {
        return botaoConsultarEx;
    }

    public void setBotaoConsultarEx(JButton botaoConsultarEx) {
        this.botaoConsultarEx = botaoConsultarEx;
    }

    public JMenu getBotaoExcluirMenu() {
        return botaoExcluirMenu;
    }

    public void setBotaoExcluirMenu(JMenu botaoExcluirMenu) {
        this.botaoExcluirMenu = botaoExcluirMenu;
    }



    public JMenu getBotaoImprimir() {
        return botaoImprimir;
    }

    public void setBotaoImprimir(JMenu botaoImprimir) {
        this.botaoImprimir = botaoImprimir;
    }

    public JMenu getBotaoEditar() {
        return botaoEditar;
    }

    public void setBotaoEditar(JMenu botaoEditar) {
        this.botaoEditar = botaoEditar;
    }

    

}
